"""Falsifiability tests for all-assistant-turn self-play attestation."""

from __future__ import annotations

import copy
import json
from itertools import islice
from pathlib import Path
from typing import Any

from tests.e2e.agentenv.trajectory import self_play_attestation

FOREIGN_CORPUS = Path(
    "/data/ryan.kim/speedlm-workloads/agentic-mixed-outcome/records.jsonl"
)


def _self_play_rows() -> list[dict[str, Any]]:
    first_turn = {
        "role": "assistant",
        "content": "I will inspect the workspace.",
        "tool_calls": [
            {
                "id": "generated-id",
                "type": "function",
                "function": {"name": "list_dir", "arguments": "{}"},
            }
        ],
        "provenance_tag": "generated",
    }
    echoed_turn = copy.deepcopy(first_turn)
    echoed_turn["provenance_tag"] = "client_supplied"
    echoed_turn["tool_calls"][0]["id"] = "client-renumbered-id"
    return [
        {
            "id": "row-1",
            "messages": [
                {"role": "user", "content": "Inspect the workspace."},
                first_turn,
            ],
        },
        {
            "id": "row-2",
            "messages": [
                {"role": "user", "content": "Inspect the workspace."},
                echoed_turn,
                {"role": "tool", "content": "note.txt", "tool_call_id": "generated-id"},
                {
                    "role": "assistant",
                    "content": "I found the note.",
                    "provenance_tag": "generated",
                },
            ],
        },
    ]


def _foreign_rows() -> list[dict[str, Any]]:
    try:
        with FOREIGN_CORPUS.open(encoding="utf-8") as handle:
            return [json.loads(line) for line in islice(handle, 2)]
    except OSError:
        # Some CI sandboxes do not mount /data.  This is the equivalent unsafe
        # replay shape: a client-supplied assistant prefix with no earlier row
        # carrying the same turn as generated by this server.
        return [
            {
                "id": "foreign-inline-1",
                "messages": [{"role": "user", "content": "Fix the issue."}],
            },
            {
                "id": "foreign-inline-2",
                "messages": [
                    {"role": "user", "content": "Fix the issue."},
                    {
                        "role": "assistant",
                        "content": "I ran a command in another model's session.",
                        "provenance_tag": "client_supplied",
                    },
                    {"role": "tool", "content": "foreign output"},
                ],
            },
        ]


def test_two_row_self_play_trajectory_attests() -> None:
    """A refusal-only checker would be safe but useless, so retain a green control.

    The second row's prefix differs only in bookkeeping and matches a generated
    turn from the earlier row.  Including tool-call IDs in identity makes it red.
    """
    result = self_play_attestation(_self_play_rows())

    assert result.attested
    assert result.rows_examined == 2
    assert result.generated_turns == 2
    assert result.prefix_assistant_turns == result.matched_prefix_turns == 1
    assert result.unmatched == ()


def test_one_character_prefix_mutation_is_refused_and_names_its_row() -> None:
    """Byte identity, not semantic similarity, is the supervision boundary.

    A one-character mutation preserves the apparent meaning while proving that
    this exact assistant turn was not generated earlier.  Fuzzy matching goes red.
    """
    rows = _self_play_rows()
    rows[1]["messages"][1]["content"] += "!"

    result = self_play_attestation(rows)

    assert not result.attested
    assert result.matched_prefix_turns == 0
    assert len(result.unmatched) == 1
    assert result.unmatched[0].startswith("row-2[1]")


def test_a_row_cannot_attest_its_prefix_with_its_own_generated_turn() -> None:
    """Generated turns become evidence only for later requests.

    A whole-batch set or a single pass that inserts generated messages first
    makes this deliberately circular row attest itself and turns the test red.
    """
    content = "This turn exists only inside one captured row."
    rows = [
        {
            "id": "self-attesting-row",
            "messages": [
                {
                    "role": "assistant",
                    "content": content,
                    "provenance_tag": "client_supplied",
                },
                {
                    "role": "assistant",
                    "content": content,
                    "provenance_tag": "generated",
                },
            ],
        }
    ]

    result = self_play_attestation(rows)

    assert not result.attested
    assert result.generated_turns == 1
    assert result.prefix_assistant_turns == 1
    assert result.matched_prefix_turns == 0
    assert result.unmatched[0].startswith("self-attesting-row[0]")


def test_foreign_replay_records_are_refused() -> None:
    """Real replay traffic must fail the exact gate self-play is meant to unlock.

    When mounted, the first two records come directly from the foreign
    ``agentic-mixed-outcome`` corpus.  Treating untagged/client-supplied
    assistant history as generated makes this test red.
    """
    rows = _foreign_rows()
    assert len(rows) == 2, "the foreign corpus did not provide the requested two records"

    result = self_play_attestation(rows)

    assert not result.attested
    assert result.rows_examined == 2
    assert result.unmatched
    row_ids = {str(row.get("id", "<no id>")) for row in rows}
    assert any(any(row_id in entry for row_id in row_ids) for entry in result.unmatched)


def test_zero_rows_cannot_attest_training_supervision() -> None:
    """No captured rows means there is no evidence on which to attest a batch.

    Returning true merely because the unmatched set is empty is a vacuous green
    check: it cannot fail on any assistant provenance because none was examined.
    """
    result = self_play_attestation([])

    assert not result.attested
    assert result.rows_examined == 0
