"""Self-play provenance: proving captured rows are legal training supervision.

WHY THIS EXISTS
---------------
Eagle3 training here is pinned to ``MaskPolicy.ALL_ASSISTANT_TURNS``, so loss
lands on *every* assistant turn in a row.  For the single-turn chat corpus that
is trivially correct.  For multi-turn traffic it is only correct if every
assistant turn in the row was produced by the verifier being trained -- otherwise
the draft head is taught to predict another model's distribution, and
``eagle3.py``'s ``dropped_client_supplied`` path drops those rows rather than
learn the wrong thing.  A real run died there: 373 of 409 rows dropped, leaving
3 against a floor of 32.

The existing escape hatch, ``trust_untagged_assistant_messages``, cannot help
gateway-captured traffic: it relabels only turns whose ``provenance_tag`` is
``None`` (``rows.py``), while capture tags every replayed prefix turn
``"client_supplied"`` explicitly.  It is also an unverified promise from the
operator, which is why an earlier attempt to unblock agentic training with it was
reverted on safety grounds.

This module replaces the promise with a measurement.  Traffic generated by
*self-play* -- the verifier driving its own tool loop against this server --
has prefix assistant turns that this same server generated seconds earlier, so
all-assistant loss on them is on-policy distillation.  :func:`self_play_attestation`
proves that per run: every ``client_supplied`` assistant turn must be
byte-identical, on content and tool-call semantics, to a ``generated`` turn from
an **earlier** row.  Order is load-bearing -- matching against the whole batch
regardless of order would let a row attest itself, which is the vacuous version
of this check.  Zero rows do not attest, because an empty batch carries no
evidence and a guard that passes on no data is this project's recurring defect.

Feed it a replayed foreign corpus and it refuses.  That is the property that
makes it worth having.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from typing import Any

__all__ = [
    "SelfPlayAttestation",
    "Trajectory",
    "assistant_fingerprint",
    "self_play_attestation",
]


def assistant_fingerprint(message: Mapping[str, Any]) -> str:
    """Content-identity of one assistant turn, ignoring bookkeeping keys.

    ``provenance_tag``, ``sampling_provenance`` and the OpenAI ``refusal``/
    ``annotations`` noise are excluded because they differ between the copy the
    server generated and the copy the client sent back -- which is the entire
    reason a naive dict comparison cannot answer this question.  ``content``,
    ``tool_calls`` and the reasoning channels ARE included, because a turn whose
    tool call differs is a different turn no matter how similar the prose.
    """
    relevant = {
        "content": message.get("content"),
        "tool_calls": _normalized_calls(message.get("tool_calls")),
        "reasoning_content": message.get("reasoning_content"),
        "thinking": message.get("thinking"),
    }
    encoded = json.dumps(relevant, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _normalized_calls(raw: object) -> list[dict[str, Any]] | None:
    """Tool calls without their ids.

    The id is a server-assigned handle. It survives the round trip in practice,
    but making identity depend on it would mean a client that renumbered calls
    -- which the OpenAI contract permits -- silently failed attestation with a
    message about content mismatch. Name and arguments are the semantic content.
    """
    if not isinstance(raw, list):
        return None
    normalized: list[dict[str, Any]] = []
    for call in raw:
        if not isinstance(call, Mapping):
            normalized.append({"unparseable": repr(call)})
            continue
        function = call.get("function")
        normalized.append(
            {
                "name": function.get("name") if isinstance(function, Mapping) else None,
                "arguments": function.get("arguments") if isinstance(function, Mapping) else None,
            }
        )
    return normalized


@dataclass(frozen=True, slots=True)
class Trajectory:
    """The captured rows belonging to one agent session, in request order."""

    instance_id: str
    rows: tuple[Mapping[str, Any], ...]


@dataclass(frozen=True, slots=True)
class SelfPlayAttestation:
    """Whether a set of captured rows is safe to train on all-assistant.

    ``unmatched`` names the rows and message indices that failed, because a
    single count turns a five-minute fix ("the reasoning channel is dropped on
    the way back") into an investigation.
    """

    attested: bool
    rows_examined: int
    generated_turns: int
    prefix_assistant_turns: int
    matched_prefix_turns: int
    unmatched: tuple[str, ...] = field(default_factory=tuple)

    @property
    def detail(self) -> str:
        if self.rows_examined == 0:
            return (
                "no rows were examined, so nothing was attested; an empty batch "
                "carries no evidence about assistant provenance"
            )
        if self.attested:
            return (
                f"{self.rows_examined} rows: {self.generated_turns} generated turns, "
                f"{self.matched_prefix_turns}/{self.prefix_assistant_turns} prefix "
                "assistant turns matched a turn this server generated earlier"
            )
        listed = "; ".join(self.unmatched[:5])
        more = (
            f" (and {len(self.unmatched) - 5} more)" if len(self.unmatched) > 5 else ""
        )
        return (
            f"{len(self.unmatched)} of {self.prefix_assistant_turns} prefix assistant "
            f"turns were not generated by this server: {listed}{more}"
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "attested": self.attested,
            "rows_examined": self.rows_examined,
            "generated_turns": self.generated_turns,
            "prefix_assistant_turns": self.prefix_assistant_turns,
            "matched_prefix_turns": self.matched_prefix_turns,
            "unmatched": list(self.unmatched),
            "detail": self.detail,
        }


def self_play_attestation(
    rows: Sequence[Mapping[str, Any]],
    *,
    reference_rows: Sequence[Mapping[str, Any]] | None = None,
) -> SelfPlayAttestation:
    """Attest that every assistant turn in ``rows`` was generated by this server.

    ``rows`` are captured trace records in the order the requests were made --
    the order matters, because a prefix turn may only be matched against a turn
    generated *earlier*.  Matching against the whole batch regardless of order
    would let a row attest itself, which is the vacuous version of this check.

    Rows are consumed as plain mappings rather than as ``TraceRecord`` so this
    module stays importable without the runtime package, and so a stored JSONL
    file can be attested after the fact by a human with no GPU.
    """
    # The evidence base and the rows under test are separable, and conflating
    # them is a real defect rather than a simplification.
    #
    # Training does not see the raw capture: a held-out split removes ~20% of
    # rows from the MIDDLE of sessions before rendering. Attesting the survivors
    # against only themselves therefore orphans every prefix turn whose
    # originating row was held out, and a genuine self-play corpus fails. That
    # is not a strict check, it is a check that cannot pass -- as useless as one
    # that cannot fail. Observed on GPU job 376291: the full 539-row capture
    # attested 2460/2460, while the 434-row training subset reported 378
    # unmatched turns for exactly this reason.
    #
    # So callers pass the COMPLETE capture as ``reference_rows`` to establish
    # what this server generated and when, while ``rows`` stays the set being
    # admitted to training.
    reference = list(reference_rows) if reference_rows is not None else list(rows)

    # Earliest position at which each generated turn appeared. "Earlier" is
    # still enforced -- a prefix turn may only cite a turn generated before the
    # row citing it -- so a row still cannot attest itself.
    first_generated: dict[str, int] = {}
    row_position: dict[str, int] = {}
    for position, row in enumerate(reference):
        identifier = row.get("id")
        if isinstance(identifier, str) and identifier not in row_position:
            row_position[identifier] = position
        messages = row.get("messages")
        if not isinstance(messages, Sequence) or isinstance(messages, (str, bytes)):
            continue
        for message in messages:
            if (
                isinstance(message, Mapping)
                and message.get("role") == "assistant"
                and message.get("provenance_tag") == "generated"
            ):
                fingerprint = assistant_fingerprint(message)
                first_generated.setdefault(fingerprint, position)

    unmatched: list[str] = []
    generated_turns = 0
    prefix_turns = 0
    matched = 0

    for index_in_rows, row in enumerate(rows):
        row_id = str(row.get("id", "<no id>"))
        messages = row.get("messages")
        if not isinstance(messages, Sequence) or isinstance(messages, (str, bytes)):
            unmatched.append(f"{row_id}: record has no messages array")
            continue

        # Where this row sits in the reference timeline. A prefix turn may only
        # cite a turn generated STRICTLY earlier, which is what stops a row from
        # attesting itself. Rows absent from the reference fall back to their
        # position among ``rows``; that only happens when no separate reference
        # was supplied, in which case the two sequences are the same object.
        position = row_position.get(row_id, index_in_rows)

        for index, message in enumerate(messages):
            if not isinstance(message, Mapping) or message.get("role") != "assistant":
                continue
            tag = message.get("provenance_tag")
            fingerprint = assistant_fingerprint(message)
            if tag == "generated":
                generated_turns += 1
                continue
            prefix_turns += 1
            origin = first_generated.get(fingerprint)
            if origin is not None and origin < position:
                matched += 1
            else:
                content = message.get("content")
                preview = content[:80] if isinstance(content, str) else repr(content)[:80]
                reason = "never generated" if origin is None else "generated later"
                unmatched.append(
                    f"{row_id}[{index}] tag={tag!r} ({reason}) content={preview!r}"
                )

    return SelfPlayAttestation(
        # An empty batch must NOT attest. ``not unmatched`` alone is true on zero
        # rows, which would hand a green verdict to a run whose capture layer
        # silently wrote nothing -- the exact shape of failure this project keeps
        # rediscovering, since the caller's guard would then be structurally
        # incapable of firing. Requiring evidence makes the check falsifiable:
        # no rows, no attestation.
        attested=bool(rows) and not unmatched,
        rows_examined=len(rows),
        generated_turns=generated_turns,
        prefix_assistant_turns=prefix_turns,
        matched_prefix_turns=matched,
        unmatched=tuple(unmatched),
    )


def iter_jsonl(lines: Iterable[str]) -> list[dict[str, Any]]:
    """Parse JSONL, skipping blanks.  Convenience for attesting a stored file."""
    parsed: list[dict[str, Any]] = []
    for number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped:
            continue
        try:
            value = json.loads(stripped)
        except json.JSONDecodeError as error:
            raise ValueError(f"line {number} is not valid JSON: {error}") from None
        if not isinstance(value, dict):
            raise ValueError(f"line {number} is not a JSON object")
        parsed.append(value)
    return parsed
