"""Chat-template contracts and assistant-span metadata."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

Conversation = Sequence[Mapping[str, Any]]
ToolSchemas = Sequence[Mapping[str, Any]]


@dataclass(frozen=True, slots=True, order=True)
class AssistantSpan:
    """Half-open character span generated by one assistant turn/channel."""

    start: int
    end: int
    turn: int
    channel: str

    def __post_init__(self) -> None:
        if self.start < 0 or self.end <= self.start:
            raise ValueError(
                f"assistant span must be non-empty and ordered, got [{self.start}, {self.end})"
            )
        if self.turn < 0:
            raise ValueError("assistant span turn must be non-negative")
        if not self.channel:
            raise ValueError("assistant span channel must be non-empty")


@runtime_checkable
class ChatTemplate(Protocol):
    """Render conversations and recover assistant supervision boundaries."""

    @property
    def name(self) -> str:
        """Stable template identifier."""
        ...

    def render(
        self,
        conversation: Conversation,
        *,
        tools: ToolSchemas = (),
    ) -> str:
        """Render one complete conversation, without a generation prompt."""
        ...

    def assistant_spans(self, rendered: str) -> tuple[AssistantSpan, ...]:
        """Return assistant payload spans in rendered character coordinates."""
        ...
